filebeat.inputs:
- type: log 
  paths:
    - /var/log/system.log
- type: tcp
  max_message_size: 10MiB
  host: "localhost:5000"
   # - /usr/share/filebeat/data/input.log
  
output.logstash:
	hosts: ["localhost:5044"]

